### ISSUE TITLE
seqrun-level: DATA_FAILED vs. COMPUTATION_FAILED

### ISSUE THREAD

**Issue by mariogiov** [NationalGenomicsInfrastructure/ngi_pipeline#178]
@vezzi we're coding the `restart_failed_jobs` functionality and we're coming to the point where we have to decide if we should restart a failed seqrun or not. At the moment, I think we're just going to say that if we decide to restart a failed sample, we're going to restart all seqruns marked as failed. The alternative is that we have two separate categories for failure (as we have discussed previously): `DATA_FAILED` vs. `COMPUTATION_FAILED`, where the former would indicate an actual problem with the data and the latter that there was something technical issue (e.g. bug in the software, filesystem failure, etc.).

My feeling is that a data failure will happen so infrequently that it's probably better to just manually delete or move that data than complicate the code with more conditionals.

**Comment by vezzi** [comment]
@mariogiov I agree with you, but do not start analysis on runs belonging to failed library prepr. If a library prep is failed (this is done manually) then do not analyse that data at all.
Otherwise, force the restarting of all and if we decide that a seq run should not be used due to some problem than the operator will manually fix the data and charon (e.g. fix the data and repopulate charon).

Does this makes sense?

**Comment by mariogiov** [comment]
@vezzi It does, and that's what we do at the moment as well -- don't restart failed library preps. Perfect!

**Comment by mariogiov** [comment]
Resolved
